### ISSUE TITLE
Dynamic Word Cloud

### ISSUE THREAD

**Issue by Datinor** [YaleDHLab/voices#10]
Some titles don’t show in records. 

Seeding with jpg failed on public computer. (ImageMagick does not identify)

Heroku scheduler was not tested.

We might not want DOWN.txt as the permanent seed file.

**Comment by duhaime** [comment]
Thanks @Datinor! I'll remove DOWN.txt and restore the original seed file. I'll also close this ticket, as #15 suggests the seeding woes are now over.
