### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Datinor** [YaleDHLab/voices#15]
[Questions on Voices documentation.docx](https://github.com/YaleDHLab/voices/files/317120/Questions.on.Voices.documentation.docx)

ImageMagick remains a stumbling block; had some questions on crossdomain.xml and descriptions.

**Comment by Datinor** [comment]
After configurations, seeding still complains of denied bucket access. I am granting excessive user rights for now.

ImageMagick stopped complaining! \o/
It was sufficient to use ruby 2.0.0.
rbenv install 2.0.0
--> choose some version x
rbenv local 2.0.0-x

**Comment by duhaime** [comment]
Yes, your AWS user will need read, write, update, and delete permissions for the bucket to which items will be uploaded.

**Comment by duhaime** [comment]
Feel free to open a pull request with semantic changes to the README if you like, @Datinor! I'll close this ticket in the interim as it's not clear what the current action items are.
