### ISSUE TITLE
Bulk upload

### ISSUE THREAD

**Issue by Datinor** [YaleDHLab/voices#17]
Successfully uploaded 
100\* 4.7mb png's + the same png's uploaded again (total 200 png's)
20*76mb videos

Website stopped operating
while videos were uploading. This took around 15-20 minutes on DHLab public computer. Changing webpage did not interrupt the server from processing the videos; that is, the website still didn't operate when I tried to back out of the upload.

**Comment by duhaime** [comment]
Excellent, all as expected. Thanks for running these tests @Datinor.
